# Global variables
# Edit variables to change the playbook's behavior
---
tm_github_url: https://github.com/TissueMAPS
tm_version: develop

tm_user: tissuemaps
tm_group: "{{ tm_user }}"

tm_home: /home/{{ tm_user }}

db_name: tissuemaps
db_master_port: 5432
db_worker1_port: 9700