---
- name: Create postgres data directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ pg_service_user }}"
    group: "{{ pg_service_group }}"
    mode: 0700
  with_items:
    - "{{ pg_master_data_dir }}"
    - "{{ pg_worker1_data_dir }}"
  tags:
    - database

- name: Initialize database
  #command: /usr/local/sbin/su-exec {{ pg_service_user }} {{ pg_exec_dir }}/pg_ctl start -w -o "-p {{ db_port }}" -D {{ db_data_directory }}/{{ db_node }} -l {{ pg_log_directory }}/postgresql-{{ db_node }}.log
  command: ./initdb --pgdata={{ item }} --auth='ident'
  args:
    chdir: "{{ pg_exec_dir }}"
  become: yes
  become_user: "{{ pg_service_user }}"
  with_items:
    - "{{ pg_master_data_dir }}"
    - "{{ pg_worker1_data_dir }}"
  tags:
    - database

- name: Configure PostgreSQL Authentication
  copy:
    src: "pg_hba.conf"
    dest: "{{ item }}/pg_hba.conf"
    owner: "{{ pg_service_user }}"
    group: "{{ pg_service_group }}"
    mode: 0700
  with_items:
    - "{{ pg_master_data_dir }}"
    - "{{ pg_worker1_data_dir }}"
  tags:
    - database

#- name: run database
#  #command: /usr/local/sbin/su-exec {{ pg_service_user }} {{ pg_exec_dir }}/pg_ctl start -w -o "-p {{ db_port }}" -D {{ db_data_directory }}/{{ db_node }} -l {{ pg_log_directory }}/postgresql-{{ db_node }}.log
#  command: ./pg_ctl --pgdata={{ item.pgdata }} -o "-p {{ item.port }}" -l master_logfile start
#  args:
#    chdir: "{{ pg_exec_dir }}"
#  become: yes
#  become_user: "{{ pg_service_user }}"
#  with_items:
#    - { pgdata: "{{ pg_master_data_dir }}", port: "{{ pg_master_port }}" }
#    - { pgdata: "{{ pg_worker1_data_dir }}", port: "{{ pg_worker1_port }}" }
#  tags:
#    - database

#- name: Preload citus extension
#  command: echo "shared_preload_libraries = 'citus'" | tee -a {{ item }}/postgresql.conf
#  become: yes
#  become_user: "{{ pg_service_user }}"
#  with_items:
#    - "{{ pg_master_data_dir }}"
#    - "{{ pg_worker1_data_dir }}"
#  tags:
#    - database

- name: Configure PostgreSQL Server
  template:
    src: "postgresql-{{ item.instance }}.conf.j2"
    dest: "{{ item.pgdata }}/postgresql.conf"
    owner: "{{ pg_service_user }}"
    group: "{{ pg_service_group }}"
    mode: 0700
  with_items:
    - { instance: 'master', pgdata: "{{ pg_master_data_dir }}" }
    - { instance: 'worker1', pgdata: "{{ pg_worker1_data_dir }}" }
  tags:
    - database

- name: Preload citus extension
  lineinfile:
    path: "{{ item }}/postgresql.conf"
    line: "shared_preload_libraries = 'citus'"
  become: yes
  become_user: "{{ pg_service_user }}"
  with_items:
    - "{{ pg_master_data_dir }}"
    - "{{ pg_worker1_data_dir }}"
  tags:
    - database

- name: Configure systemd postgres instances
  template:
    src: "postgres-{{ item }}.service.j2"
    dest: "/etc/systemd/system/postgres-{{ item }}.service"
    mode: 664
  with_items:
    - "master"
    - "worker1"
  tags:
    - database