---
- name: Add PostgreSQL repository
  yum_repository:
    name: postgresql
    description: PostgreSQL YUM repo
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/{{ ansible_os_family | lower }}/rhel-{{ ansible_distribution_version[0] }}-x86_64

- name: Get Citus repository
  get_url:
    url: https://install.citusdata.com/community/rpm.sh
    dest: /tmp/citus_rpm.sh
    mode: 0770
  tags:
    - database

- name: Add Citus repository
  command: "/tmp/citus_rpm.sh"
  tags:
    - database

- name: Install PostgreSQL, Citus and PostGIS
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - postgresql{{ postgresql_version | regex_replace('(\.)', '') }}-contrib
    - citus{{ citus_version | regex_replace('(\.)', '') }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - postgis{{ postgis_version[0] }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - python-psycopg2
  tags:
    - database

#- name: Install setfacl support
#  yum:
#    name: acl
#  tags:
#    - database