---
# 1) Build web application
- name: Clone the TMUI repository
  git:
    repo: 'https://github.com/TissueMAPS/TmUi.git'
    dest: /tmp/tm-ui-repo
    version: "{{ tm_version }}"
  tags:
    - tm-ui

- name: ls -ahl /tmp/tm-ui-repo
  command: ls -ahl /tmp/tm-ui-repo
  register: ls

- name: Debug - ls -ahl /tmp/tm-ui-repo
  debug:
    msg: "stdout: {{ ls.stdout }}"

- name: Install NodeJS and NPM
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - nodejs-6.14.0
    - npm-3.10.10
  tags:
    - tm-ui

- name: Install "bower" and "gulp" node.js package globally.
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - bower
    - gulp
  tags:
    - tm-ui

- name: Install "TM-UI" based on package.json.
  npm:
    path: /tmp/tm-ui-repo/src
  tags:
    - tm-ui

- name: Install "TM-UI" packages based on bower.json.
  bower:
    path: /tmp/tm-ui-repo/src
  tags:
    - tm-ui

- name: Install "TM-UI" packages based on gulpfile.js.
  command: gulp build --prod
  args:
    chdir: "/tmp/tm-ui-repo/src"
  tags:
    - tm-ui

# 2) Copy web application
- name: Creates web app directory
  file:
    path: /var/www/tissuemaps/tmui/
    state: directory
    owner: uwsgi
    group: nginx
    recurse: yes
  tags:
    - tm-ui

- name: copy builded web app
  copy:
    src: /tmp/tm-ui-repo/src/build/
    dest: /var/www/tissuemaps/tmui/
    owner: uwsgi
    group: nginx
  tags:
    - tm-ui

- name: Fix the selinux contexts on the web app directory
  shell: restorecon -r /var/www/tissuemaps/
  tags:
    - tm-ui
