---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'base', tags: 'base'}

- hosts: tm-db-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'database', tags: 'database'}

- hosts: tm-web-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'web-service', tags: 'web-service'}
    - {role: 'tm-ui', tags: 'tm-ui'}
    - {role: 'jt-library', tags: 'jt-library'}
    - {role: 'tm-library', tags: 'tm-library'}