---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'base', tags: 'base'}

- hosts: database-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'db-service', tags: 'db-service'}

- hosts: tissuemaps-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'web-service', tags: 'web-service'}
    - {role: 'tm-ui', tags: 'tm-ui'}
    - {role: 'jt-library', tags: 'jt-library'}
    - {role: 'tm-library', tags: 'tm-library'}
    - {role: 'tm-server', tags: 'tm-server'}

- hosts: client-machines
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - {role: 'tm-client', tags: 'tm-client'}