---
- name: Get Citus repository
  command: wget https://install.citusdata.com/community/rpm.sh -O {{ tm_home }}/citus_rpm.sh
  args:
    executable=/bin/bash
    chdir={{ tm_home }}
  tags:
    - database

- name: Make Citus install script executable
  file:
    path={{ tm_home }}/citus_rpm.sh
    mode=0770
  tags:
    - database

- name: Add Citus repository
  command: "{{ tm_home }}/citus_rpm.sh"
  tags:
    - database

- name: Install PostgreSQL, Citus and PostGIS
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - postgresql{{ postgresql_version | regex_replace('(\.)', '') }}-contrib
    - citus{{ citus_version | regex_replace('(\.)', '') }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - postgis{{ postgis_version[0] }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - python-psycopg2
  tags:
    - database

#- name: Install setfacl support
#  yum:
#    name: acl
#  tags:
#    - database

- name: Set directory for PostgreSQL executables
  set_fact:
    db_executable_directory: /usr/pgsql-{{ postgresql_version }}/bin
  tags:
    - database

- name: Set directory for default PostgreSQL cluster
  set_fact:
    db_default_cluster_data_directory: /var/lib/pgsql-{{ postgresql_version }}/data
  tags:
    - database