---
#- name: Get Citus repository
#  command: wget https://install.citusdata.com/community/rpm.sh -O /tmp/citus_rpm.sh
#  #args:
#  #  executable=/bin/bash
#  #  chdir={{ tm_home }}
#  tags:
#    - database
- name: Add PostgreSQL repository
  yum_repository:
    #yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
    name: postgresql
    description: PostgreSQL YUM repo
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/{{ ansible_os_family | lower }}/rhel-{{ ansible_distribution_version[0] }}-x86_64

- name: Get Citus repository
  get_url:
    url: https://install.citusdata.com/community/rpm.sh
    dest: /tmp/citus_rpm.sh
    mode: 0770
  tags:
    - database

#- name: Make Citus install script executable
#  file:
#    #path={{ tm_home }}/citus_rpm.sh
#    path=/tmp/citus_rpm.sh
#    mode=0770
#  tags:
#    - database

- name: Add Citus repository
  #command: "{{ tm_home }}/citus_rpm.sh"
  command: "/tmp/citus_rpm.sh"
  tags:
    - database

- name: Install PostgreSQL, Citus and PostGIS
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - postgresql{{ postgresql_version | regex_replace('(\.)', '') }}-contrib
    - citus{{ citus_version | regex_replace('(\.)', '') }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - postgis{{ postgis_version[0] }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - python-psycopg2
  tags:
    - database

#- name: Install setfacl support
#  yum:
#    name: acl
#  tags:
#    - database

- name: Set directory for PostgreSQL executables
  set_fact:
    db_executable_directory: /usr/pgsql-{{ postgresql_version }}/bin
  tags:
    - database

- name: Set directory for default PostgreSQL cluster
  set_fact:
    db_master_data_directory: /var/lib/pgsql-{{ postgresql_version }}/citus-{{ citus_version }}/master
    db_worker1_data_directory: /var/lib/pgsql-{{ postgresql_version }}/citus-{{ citus_version }}/worker1
  tags:
    - database