---
- name: Clone the JT Library repository
  git:
    repo: 'https://github.com/TissueMAPS/JtLibrary.git'
    dest: /tmp/jt-library-repo
    version: "{{ tm_version }}"
  tags:
    - jt-library

#- name: ls -ahl /tmp/jt-library-repo
#  command: ls -ahl /tmp/jt-library-repo
#  register: ls

#- name: Debug - ls -ahl /tmp/jt-library-repo
#  debug:
#    msg: "stdout: {{ ls.stdout }}"

- name: Install Python-PIP Python-DEVEL and GCC
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - python-pip
    - python-devel
    - gcc
  tags:
    - jt-library

- name: Install "numpy" and "Cython" packages via PIP.
  pip:
    name: "{{ item }}"
  with_items:
    - numpy
    - Cython
  tags:
    - jt-library

- name: Install/Update "setuptools" packages via PIP.
  pip:
    name: setuptools
    state: latest
  tags:
    - jt-library

- name: Install "JTLibrary" packages via PIP.
  pip:
    name: "/tmp/jt-library-repo/python/jtlibrary"
    extra_args: --user
  tags:
    - jt-library
