---
#- name: Ensure PostgreSQL is restarted
#  systemd:
#    name: "postgres-{{ item }}"
#    state: started
#    daemon_reload: yes
#  with_items:
#    - "master"
#    - "worker1"
#  tags:
#    - database

#- name: Create nginx group
#  group:
#    name: "{{ nginx_group }}"
#    state: present

#- name: Create nginx user
#  user:
#    name: "{{ nginx_user }}"
#    groups:
#     - "{{ nginx_group }}"
#    state: present
#    shell: /bin/bash
#    system: no
#    createhome: no
#  tags:
#    - base


- name: Run Nginx in background
  shell: nohup nginx -g "daemon off;" </dev/null >/dev/null 2>&1 &
  become: yes
  #become_user: "{{ web_user }}"
  become_user: "nginx"
  tags:
    - web-service

- name: Run Uwsgi in background
  shell: nohup uwsgi --http :8008 </dev/null >/dev/null 2>&1 &
  become: yes
  become_user: "uwsgi"
  tags:
    - web-service

#- name: Debug - Active Worker Nodes
#  debug:
#    msg: "Active Worker Nodes: {{ active_worker_nodes.stdout }}"