---
# EXTRACT TO BASE IMAGE!!!!!!!!!!!!!!!!!!!!!!!!
- name: Install Python-PIP Python-DEVEL and GCC
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - python-pip
    - python-devel
    - gcc
  tags:
    - jt-library

- name: Clone the TM Client repository
  git:
    repo: 'https://github.com/TissueMAPS/TmClient.git'
    dest: /tmp/tm-client-repo
    version: "{{ tm_version }}"
  tags:
    - tm-client

- name: Install "TM Client" packages via PIP.
  pip:
    name: "/tmp/tm-client-repo"
    extra_args: --user
  tags:
    - tm-client
