---
- name: Create gc3pie configuration directory
  file:
    path: "/home/{{ tm_service_user }}/.gc3"
    state: directory
    owner: "{{ tm_service_user }}"
    group: "{{ tm_service_group }}"
    mode: 0775
  tags:
    - tm-library

- name: Create gc3pie configuration file
  copy:
    dest: "/home/{{ tm_service_user }}/.gc3/gc3pie.conf"
    content: |
      [auth/noauth]
      type=none
      
      [resource/localhost]
      enabled=true
      type=shellcmd
      spooldir=/var/tmp
      auth=noauth
      transport=local
      max_cores=1
      max_cores_per_job=1
      max_memory_per_core=1 GB
      max_walltime=2 hours
      architecture=x64_64
      override = no
    force: no
    owner: "{{ tm_service_user }}"
    group: "{{ tm_service_group }}"
    mode: 0775
  tags:
    - tm-library