---
- name: Install BioFormats
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  tags:
    - tm-library

- name: Clone the BioFormats repository
  git:
    repo: 'https://github.com/openmicroscopy/bioformats.git'
    dest: /tmp/jt-library-repo
    version: "v5.7.1"
  tags:
    - tm-library

- name: copy BioFormats Tools
  copy:
    src: /tmp/jt-library-repo/tools/
    dest: /opt/bioformattools-5.7.1/
  tags:
    - tm-library

- name: Clone the GC3Pie repository
  git:
    repo: 'https://github.com/TissueMAPS/gc3pie.git'
    dest: /tmp/gc3pie-repo
    version: "master"
  tags:
    - tm-library

- name: Install "setuptools" packages via PIP.
  pip:
    name: setuptools
    state: latest
  tags:
    - tm-library

- name: Uninstall "gssapi" packages via PIP.
  pip:
    name: gssapi
    state: absent
  tags:
    - tm-library

- name: Install "GC3Pie" packages via PIP.
  pip:
    name: "/tmp/gc3pie-repo"
    extra_args: --user
  tags:
    - tm-library
