---
- name: Ensure CentOS distribution in case of RedHat OS family
  fail:
    msg: Requires CentOS distribution!
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'CentOS'

- name: Ensure correct CentOS distribution version in case of RedHat OS family
  fail:
    msg: Requires CentOS distribution version >= 7!
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_version[0]|int < 7