---
- name: Create tissuemaps group
  group:
    name: "{{ tm_service_group }}"
    state: present

- name: Create tissuemaps service user
  user:
    name: "{{ tm_service_user }}"
    groups:
     - "{{ tm_service_group }}"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/{{ tm_service_user }}
  tags:
    - base