---
- name: Prepare nginx.conf
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - tm-server

- name: Add tissueaps nginx configuration
  copy:
    src: "tissuemaps.conf"
    dest: "/etc/nginx/conf.d/tissuemaps.conf"
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - tm-server

- name: Create nginx log directory
  file:
    path: "/var/log/nginx"
    state: directory
    owner: nginx
    group: nginx
    mode: 0766
  tags:
    - tm-server

- name: Prepare uwsgi.ini
  lineinfile:
    path: "/etc/uwsgi.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'uid = uwsgi', line: '#uid = uwsgi' }
    - { regexp: 'gid = uwsgi', line: '#gid = uwsgi' }
    - { regexp: 'cap = setgid,setuid', line: '#cap = setgid,setuid' }
  tags:
    - tm-server

- name: Add tissueaps uwsgi configuration
  template:
    src: "tissuemaps.ini.j2"
    dest: "/etc/uwsgi.d/tissuemaps.ini"
    mode: 0700
    owner: uwsgi
    group: uwsgi
  tags:
    - tm-server

- name: Create uwsgi log directory for tissuemaps
  file:
    path: "/var/log/uwsgi"
    state: directory
    owner: "{{ tm_service_user }}"
    group: uwsgi
    mode: 0775
  tags:
    - tm-server

- name: Touch uwsgi log file for tissuemaps
  copy:
    content: ""
    dest: "/var/log/uwsgi/tissuemaps.log"
    force: no
    owner: uwsgi
    group: uwsgi
    mode: 0644
  tags:
    - tm-server

- name: Create uwsgi pid directory for tissuemaps
  file:
    path: "/var/run/uwsgi/"
    state: directory
    owner: uwsgi
    group: uwsgi
    mode: 0644
  tags:
    - tm-server

- name: Create uwsgi socket directory for tissuemaps
  file:
    path: "/var/run/uwsgi-tissuemaps"
    state: directory
    # owner: "{{ tm_service_user }}"
    owner: uwsgi
    group: nginx
    mode: 0660
  tags:
    - tm-server

    